(lang dune 3.0)
(name mixos_pkgmgr)
(version 0.1.0)

(package
 (name mixos_pkgmgr)
 (synopsis "MixOS Package Manager Service")
 (description "Internal package management service for MixOS")
 (depends
  (ocaml (>= 4.14))
  dune
  lwt
  lwt_ppx
  unix
  yojson
  ppx_deriving
  ppx_deriving_yojson
  digestif
  tar))
