# MIXOS GO systemd-networkd configuration
# /etc/systemd/networkd.conf

[Network]
# Enable DHCP on all interfaces by default
# SpeedMeter=yes
# ManageForeignRoutes=yes

[DHCP]
# DUIDType=vendor
# DUIDRawData=
