package backend

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/mixos/mix-installer/pkg/models"
)

// BootloaderManager handles bootloader installation
type BootloaderManager struct {
	dryRun    bool
	mountRoot string
}

// NewBootloaderManager creates a new bootloader manager
func NewBootloaderManager(dryRun bool, mountRoot string) *BootloaderManager {
	if mountRoot == "" {
		mountRoot = "/mnt"
	}
	return &BootloaderManager{
		dryRun:    dryRun,
		mountRoot: mountRoot,
	}
}

// DetectBootMode detects the current boot mode (UEFI or Legacy)
func (b *BootloaderManager) DetectBootMode() string {
	if _, err := os.Stat("/sys/firmware/efi"); err == nil {
		return "uefi"
	}
	return "legacy"
}

// InstallGRUB installs GRUB bootloader
func (b *BootloaderManager) InstallGRUB(config models.BootloaderConfig) error {
	if b.dryRun {
		fmt.Printf("[DRY RUN] Would install GRUB: %+v\n", config)
		return nil
	}

	bootMode := b.DetectBootMode()

	if bootMode == "uefi" {
		return b.installGRUBEFI(config)
	}
	return b.installGRUBLegacy(config)
}

// installGRUBEFI installs GRUB for UEFI systems
func (b *BootloaderManager) installGRUBEFI(config models.BootloaderConfig) error {
	efiDir := config.EFIDir
	if efiDir == "" {
		efiDir = "/boot/efi"
	}

	bootloaderID := config.BootloaderID
	if bootloaderID == "" {
		bootloaderID = "MIXOS"
	}

	// Install GRUB
	args := []string{
		"--target=x86_64-efi",
		"--efi-directory=" + filepath.Join(b.mountRoot, efiDir),
		"--bootloader-id=" + bootloaderID,
		"--root-directory=" + b.mountRoot,
		"--recheck",
	}

	cmd := exec.Command("grub-install", args...)
	cmd.Env = append(os.Environ(), "GRUB_DISABLE_OS_PROBER=true")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("grub-install failed: %w\n%s", err, output)
	}

	// Generate GRUB config
	if err := b.generateGRUBConfig(); err != nil {
		return err
	}

	return nil
}

// installGRUBLegacy installs GRUB for Legacy BIOS systems
func (b *BootloaderManager) installGRUBLegacy(config models.BootloaderConfig) error {
	device := config.Device
	if device == "" {
		return fmt.Errorf("device required for legacy GRUB installation")
	}

	// Install GRUB to MBR
	args := []string{
		"--target=i386-pc",
		"--root-directory=" + b.mountRoot,
		"--recheck",
		device,
	}

	cmd := exec.Command("grub-install", args...)
	cmd.Env = append(os.Environ(), "GRUB_DISABLE_OS_PROBER=true")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("grub-install failed: %w\n%s", err, output)
	}

	// Generate GRUB config
	if err := b.generateGRUBConfig(); err != nil {
		return err
	}

	return nil
}

// generateGRUBConfig generates GRUB configuration
func (b *BootloaderManager) generateGRUBConfig() error {
	grubCfgPath := filepath.Join(b.mountRoot, "boot", "grub", "grub.cfg")

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(grubCfgPath), 0755); err != nil {
		return err
	}

	// Try grub-mkconfig first
	cmd := exec.Command("grub-mkconfig", "-o", grubCfgPath)
	cmd.Env = append(os.Environ(),
		"GRUB_DISABLE_OS_PROBER=true",
		fmt.Sprintf("GRUB_CMDLINE_LINUX_DEFAULT=quiet splash"),
	)

	if output, err := cmd.CombinedOutput(); err != nil {
		// Fallback to manual config
		return b.writeManualGRUBConfig(grubCfgPath)
	} else {
		_ = output // Config generated successfully
	}

	return nil
}

// writeManualGRUBConfig writes a manual GRUB configuration
func (b *BootloaderManager) writeManualGRUBConfig(path string) error {
	config := `# GRUB Configuration for MIXOS GO
# Generated by mix-installer

set default=0
set timeout=5

# Load modules
insmod part_gpt
insmod part_msdos
insmod ext2
insmod fat

# Set root
search --no-floppy --label MIXOS_ROOT --set=root

# Menu entries
menuentry "MIXOS GO" --class mixos --class os {
    linux /boot/vmlinuz root=LABEL=MIXOS_ROOT rw quiet splash
    initrd /boot/initramfs.img
}

menuentry "MIXOS GO (Recovery Mode)" --class mixos --class os {
    linux /boot/vmlinuz root=LABEL=MIXOS_ROOT rw single
    initrd /boot/initramfs.img
}

menuentry "MIXOS GO (Safe Mode)" --class mixos --class os {
    linux /boot/vmlinuz root=LABEL=MIXOS_ROOT rw nomodeset
    initrd /boot/initramfs.img
}
`

	return os.WriteFile(path, []byte(config), 0644)
}

// WriteGRUBDefaults writes GRUB default configuration
func (b *BootloaderManager) WriteGRUBDefaults() error {
	defaultsPath := filepath.Join(b.mountRoot, "etc", "default", "grub")

	if b.dryRun {
		fmt.Printf("[DRY RUN] Would write GRUB defaults to %s\n", defaultsPath)
		return nil
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(defaultsPath), 0755); err != nil {
		return err
	}

	config := `# GRUB boot loader configuration
# Generated by mix-installer

GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="MIXOS GO"
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""

# Uncomment to disable graphical terminal
#GRUB_TERMINAL=console

# Resolution
GRUB_GFXMODE=auto
GRUB_GFXPAYLOAD_LINUX=keep

# Disable OS prober
GRUB_DISABLE_OS_PROBER=true
`

	return os.WriteFile(defaultsPath, []byte(config), 0644)
}

// InstallSystemdBoot installs systemd-boot (alternative to GRUB)
func (b *BootloaderManager) InstallSystemdBoot(config models.BootloaderConfig) error {
	if b.dryRun {
		fmt.Printf("[DRY RUN] Would install systemd-boot: %+v\n", config)
		return nil
	}

	efiDir := config.EFIDir
	if efiDir == "" {
		efiDir = "/boot/efi"
	}

	espPath := filepath.Join(b.mountRoot, efiDir)

	// Install bootctl
	cmd := exec.Command("bootctl", "--esp-path="+espPath, "install")
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("bootctl install failed: %w\n%s", err, output)
	}

	// Write loader config
	if err := b.writeLoaderConfig(espPath); err != nil {
		return err
	}

	// Write boot entry
	if err := b.writeBootEntry(espPath); err != nil {
		return err
	}

	return nil
}

// writeLoaderConfig writes systemd-boot loader configuration
func (b *BootloaderManager) writeLoaderConfig(espPath string) error {
	loaderPath := filepath.Join(espPath, "loader", "loader.conf")

	if err := os.MkdirAll(filepath.Dir(loaderPath), 0755); err != nil {
		return err
	}

	config := `default mixos.conf
timeout 5
console-mode max
editor no
`

	return os.WriteFile(loaderPath, []byte(config), 0644)
}

// writeBootEntry writes a systemd-boot entry
func (b *BootloaderManager) writeBootEntry(espPath string) error {
	entriesPath := filepath.Join(espPath, "loader", "entries")
	entryPath := filepath.Join(entriesPath, "mixos.conf")

	if err := os.MkdirAll(entriesPath, 0755); err != nil {
		return err
	}

	entry := `title   MIXOS GO
linux   /vmlinuz
initrd  /initramfs.img
options root=LABEL=MIXOS_ROOT rw quiet splash
`

	return os.WriteFile(entryPath, []byte(entry), 0644)
}

// UpdateInitramfs regenerates initramfs
func (b *BootloaderManager) UpdateInitramfs() error {
	if b.dryRun {
		fmt.Printf("[DRY RUN] Would update initramfs\n")
		return nil
	}

	// Try different initramfs tools
	tools := []struct {
		cmd  string
		args []string
	}{
		{"mkinitcpio", []string{"-P"}},
		{"dracut", []string{"--force"}},
		{"update-initramfs", []string{"-u"}},
	}

	for _, tool := range tools {
		if _, err := exec.LookPath(tool.cmd); err == nil {
			cmd := exec.Command("chroot", append([]string{b.mountRoot, tool.cmd}, tool.args...)...)
			if output, err := cmd.CombinedOutput(); err != nil {
				return fmt.Errorf("%s failed: %w\n%s", tool.cmd, err, output)
			}
			return nil
		}
	}

	return fmt.Errorf("no initramfs tool found")
}

// GetRecommendedBootloader returns the recommended bootloader
func (b *BootloaderManager) GetRecommendedBootloader() models.BootloaderConfig {
	bootMode := b.DetectBootMode()

	config := models.BootloaderConfig{
		Type:         "grub",
		BootloaderID: "MIXOS",
	}

	if bootMode == "uefi" {
		config.Target = "x86_64-efi"
		config.EFIDir = "/boot/efi"
	} else {
		config.Target = "i386-pc"
	}

	return config
}

// VerifyBootloader verifies bootloader installation
func (b *BootloaderManager) VerifyBootloader(config models.BootloaderConfig) error {
	bootMode := b.DetectBootMode()

	if bootMode == "uefi" {
		// Check EFI files exist
		efiDir := config.EFIDir
		if efiDir == "" {
			efiDir = "/boot/efi"
		}

		bootloaderID := config.BootloaderID
		if bootloaderID == "" {
			bootloaderID = "MIXOS"
		}

		efiPath := filepath.Join(b.mountRoot, efiDir, "EFI", bootloaderID, "grubx64.efi")
		if _, err := os.Stat(efiPath); os.IsNotExist(err) {
			return fmt.Errorf("EFI bootloader not found at %s", efiPath)
		}
	}

	// Check GRUB config exists
	grubCfg := filepath.Join(b.mountRoot, "boot", "grub", "grub.cfg")
	if _, err := os.Stat(grubCfg); os.IsNotExist(err) {
		return fmt.Errorf("GRUB config not found at %s", grubCfg)
	}

	return nil
}

// SetupEFIFallback sets up EFI fallback boot entry
func (b *BootloaderManager) SetupEFIFallback(config models.BootloaderConfig) error {
	if b.dryRun {
		fmt.Printf("[DRY RUN] Would setup EFI fallback\n")
		return nil
	}

	efiDir := config.EFIDir
	if efiDir == "" {
		efiDir = "/boot/efi"
	}

	bootloaderID := config.BootloaderID
	if bootloaderID == "" {
		bootloaderID = "MIXOS"
	}

	// Copy to fallback location
	srcPath := filepath.Join(b.mountRoot, efiDir, "EFI", bootloaderID, "grubx64.efi")
	dstDir := filepath.Join(b.mountRoot, efiDir, "EFI", "BOOT")
	dstPath := filepath.Join(dstDir, "BOOTX64.EFI")

	if err := os.MkdirAll(dstDir, 0755); err != nil {
		return err
	}

	// Copy file
	input, err := os.ReadFile(srcPath)
	if err != nil {
		return err
	}

	return os.WriteFile(dstPath, input, 0755)
}

// GetBootEntries returns current boot entries (for UEFI)
func (b *BootloaderManager) GetBootEntries() ([]string, error) {
	if b.DetectBootMode() != "uefi" {
		return nil, fmt.Errorf("boot entries only available in UEFI mode")
	}

	output, err := exec.Command("efibootmgr", "-v").Output()
	if err != nil {
		return nil, err
	}

	var entries []string
	for _, line := range strings.Split(string(output), "\n") {
		if strings.HasPrefix(line, "Boot") && strings.Contains(line, "*") {
			entries = append(entries, line)
		}
	}

	return entries, nil
}
